import "./globals.css";


export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html lang="en" about="it is me hello how are you">
            <body>{children}</body>
        </html>
    );
}
